config/routes.rb
Rails.application.routes.draw do

  # Homepage
  root to: 'pages#index'
  root 'pages#index'

  resources :listings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :category, :address)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>(w)holistic</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex h-100 p-3 mx-auto flex-column">

      <header class="masthead">
        <div class="inner">
          <h3><%= link_to '(w)holistic', root_path, class: 'masthead-brand' %></h3>
          <nav class="nav nav-masthead justify-content-center">
            <%= link_to "Home", root_path, class: 'nav-link' %>
            <%= link_to "Listings", listings_path, class: 'nav-link' %>
          </nav>
        </div>
      </header>

      <%= yield %>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Always free. Forever and ever.</p>
        </div>
      </footer>

    </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>
  <div class="row">
    <div class="">
      <h1>Listings</h1>
      <table class="table table-striped table-hover table-bordered">
      <thead class="thead-light">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Category</th>
          <th>Address</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @listings.each do |listing| %>
          <tr>
            <td><%= listing.name %></td>
            <td><%= listing.description %></td>
            <td><%= listing.category %></td>
            <td><%= listing.address %></td>
            <td><%= link_to 'Show', listing %></td>
            <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
            <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
      </table>
      <%= link_to 'New Listing', new_listing_path %>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @listing.category %>
</p>

<p>
  <strong>Address:</strong>
  <%= @listing.address %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/pages/index.html.erb
<div class="mt-auto">
  <main role="main" class="inner cover">
    <div class="text-center">
    <h1 class="cover-heading">VISION</h1>

    <p class="lead">(w)holistic aims to connect, empower and revitalize our community with resources that will help
      the individual live whole.
    </p>

    <p class="lead">
      <%= link_to "SEARCH LISTINGS", listings_path, class: 'btn btn-lg btn-secondary' %>
    </p>
    </div>
  </main>
</div>